# Generated by Django 3.0.7 on 2020-10-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Juvenile', max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='approaches',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='chasing',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='climbing',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='date',
            field=models.DateField(blank=True, help_text='Date', null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='eating',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='foraging',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='indifferent',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='kuks',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='moans',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='other_activities',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='primary_fur_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '')], max_length=16),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='quaas',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='running',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='runs_from',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=16),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='specific_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='tail_flags',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='tail_twitches',
            field=models.BooleanField(blank=True),
        ),
    ]
