# Generated by Django 3.0.7 on 2020-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqtracker', '0002_auto_20201015_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightings',
            name='id',
        ),
        migrations.AlterField(
            model_name='sightings',
            name='date',
            field=models.DateField(blank=True, help_text='The date format must be YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='latitude',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='longitude',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='primary_fur_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='unique_squirrel_id',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
